name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kkhys
          repo: kkhys
          committer_token: ${{ github.token }}
          committer_branch: main
          committer_message: Update metrics
          filename: metrics.svg
          config_timezone: Asia/Tokyo
          config_gemoji: yes
          config_twemoji: yes
          config_display: large
          config_padding: 0, 5%
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 200
          plugin_reactions_details: count, percentage
          plugin_reactions_ignored: bot
          plugin_followup: yes
          plugin_followup_sections: user #
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: octonaut
          plugin_achievements_limit: 0
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_shuffle: yes
          plugin_anilist_user: .user.login
          plugin_anilist_limit_characters: 22
